from pyKey import pressKey, releaseKey, press, sendSequence, showKeys
from time import *
sleep(4)

#if True:
while True:
    pressKey("UP")
    sleep(1)
    pressKey("DEL")
    sleep(3)
    releaseKey("DEL")
    sleep(2)
    pressKey("RIGHT")
    sleep(0.4)
    releaseKey("RIGHT")
    sleep(1)
    pressKey("LEFT")
    sleep(0.1)
    releaseKey("LEFT")
    sleep(1)
    pressKey("LEFT")
    sleep(0.9)
    releaseKey("LEFT")
    sleep(1.5)
    pressKey("RIGHT")
    sleep(0.5)
    releaseKey("RIGHT")
    sleep(3)
    sleep(1.1)
    pressKey("LEFT")
    sleep(2)
    releaseKey("LEFT")
    sleep(2.1)
    pressKey("LEFT")
    sleep(1.94)
    releaseKey("LEFT")
    sleep(3)
    pressKey("RIGHT")
    sleep(0.1)
    releaseKey("RIGHT")
    sleep(13)
    releaseKey("UP")